server:
  port: 9001

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka-service2
  client:
    service-url:
      defaultZone: http://eureka-service1:9002/eureka/
    register-with-eureka: false
    fetch-registry: false