server:
  port: 9005

spring:
  application:
    name: spring-demo
  profiles:
    active: dev

process:
  name: spring-demo2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka/
    register-with-eureka: true
    fetch-registry: true