eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    enabled: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

spring:
  security:
    user:
      name: eureka
      password: 123456

