eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'