zuul:
  routes:
    api-a:
      path: /consumer/**
#      stripPrefix: false
#      serviceId: consumer-demo
      url: forward:/consumer
    api-b:
      path: /provider/**
      serviceId: provider-demo
  sensitive-headers: Cookie,Set-Cookie,Authorization
  retryable: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator

feign:
  name: provider-demo