server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9091


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: spring-cloud-demo
