server:
  port: 9102

spring:
  application:
    name: feign-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
    fetch-registry: true
    register-with-eureka: true